version: '3'  # version of compose format

services:
  laptop-service:
    build: ./laptop
    volumes:
      - ./laptop:/usr/src/app
    ports:
      - 5001:80  # host:container
    depends_on:
      - web

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80  # host:container
    depends_on:
      - laptop-service  # website is not going to work unless laptop-service is running

  web:
    build: ./Project6
    command: flask_brevets.py
    ports:
     - "5002:5000" #our calculator will be on 5002
    volumes:
     - ./Project6:/todo
    links:
     - db
  db:
    image: mongo:3.0.2
